### ISSUE TITLE
where chained with orWhere fails

### ISSUE THREAD

**Issue by dimitrigogios** [saintsystems/odata-client-php#101]
Hi, I'm trying to do a `where` chained together with an `orWhere`. But it fails:

```
$orders1 = $odataClient->from('orders')
                ->where([
                    ['Sell_to_Customer_No', '=', $customerNo],
                    ["Document_No", ">=", $term],
                ])
                ->orWhere([
                    ['Sell_to_Customer_No', '=', $customerNo],
                    ["No", ">=", $term],
                ])
                ->order("Document_No", "desc")
                ->get()
```

**Comment by anderly** [comment]
Can you tell what the generated URL is?

Might be worth putting together a quick unit test like those in [BuilderTest.php](https://github.com/saintsystems/odata-client-php/blob/master/tests/Query/BuilderTest.php) with your where and orWhere calls and generating the request URI to track down where the issue is.

**Comment by dimitrigogios** [comment]
No I can't see the generated URL?

**Comment by anderly** [comment]
Added a test to cover this in 5318323, but unable to reproduce.
