### ISSUE TITLE
How do we use DateTimes?

### ISSUE THREAD

**Issue by ds620107** [saintsystems/odata-client-php#74]
How do we use datetimes in a where clause? I've tried passing a timestamp and datetimes in different formats but it quotes the dates no matter what.

**Comment by gruler** [comment]
Did you figure this out? i am also having this issue.

**Comment by ds620107** [comment]
Not really, I'm going with a dirty workaround for now.

```
->where("CreatedDateUtc gt " . $the_date->format('Y-m-d\TH:i:s\Z') . ")&1", "=", "1")
```

You can write manually into the url by appending &1=1 in the where clause. I know this is a terrible solution, but I'm sticking to this for now until it gets fixed.

**Comment by gruler** [comment]
I figured it out. The code in Grammar.php looks for only dates that look like: '2020-01-11T23:59:59Z'

This is a sample where clause ->where('ModificationTimestamp','>','2020-01-11T23:59:59Z')

If the format of your date matches this ('Y-m-d\TH:i:sT'), it will not quote the value. 
Otherwise it thinks it is a string and wants to add quotes. 
So just a plain Date, 2021-01-01 will have quotes added which makes the query unusable.

I hope that helps.

**Comment by ds620107** [comment]
That's interesting, because that's the format I was outputting it in and it didn't work for me. I'll have to try it again.
