### ISSUE TITLE
$count needs to be $count=true

### ISSUE THREAD

**Issue by cooperRjp** [saintsystems/odata-client-php#91]
The $count in the api which i'm querying needs to be set to $count=true, is there a way to do so?

**Comment by tavy315** [comment]
@cooperRjp if you take a look at [oData's URI convensions](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) or [Addressing the Count of a Collection](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection), seems that $count doesn't need anything else.

Also, keep in mind that [$count can be used in the path](https://services.odata.org/V4/Northwind/Northwind.svc/Customers/$count?$filter=Country%20eq%20%27Germany%27), but also [in query as $count=true](https://services.odata.org/V4/Northwind/Northwind.svc/Customers?$count=true&$filter=Country%20eq%20%27Germany%27).

I think the second method is also [implemented](https://github.com/saintsystems/odata-client-php/blob/master/src/Query/Grammar.php#L414), so you can probably try the `totalCount()` method instead of `count()`.

Hope this information helps.
